## Hello Python !!

In [1]:
print('Hello Python !!')

Hello Python !!


## Python 註解

In [2]:
print('Hello Python !!') #我的第一個python程式

Hello Python !!


## The Zen of Python

In [3]:
import this

The Zen of Python, by Tim Peters

Beautiful is better than ugly.
Explicit is better than implicit.
Simple is better than complex.
Complex is better than complicated.
Flat is better than nested.
Sparse is better than dense.
Readability counts.
Special cases aren't special enough to break the rules.
Although practicality beats purity.
Errors should never pass silently.
Unless explicitly silenced.
In the face of ambiguity, refuse the temptation to guess.
There should be one-- and preferably only one --obvious way to do it.
Although that way may not be obvious at first unless you're Dutch.
Now is better than never.
Although never is often better than *right* now.
If the implementation is hard to explain, it's a bad idea.
If the implementation is easy to explain, it may be a good idea.
Namespaces are one honking great idea -- let's do more of those!


## 變數命名規則

In [4]:
_variable = 1 

In [5]:
variable = 1 

In [6]:
first_variable = 1

In [7]:
$variable = 1

SyntaxError: invalid syntax (<ipython-input-7-1ea8277c23c2>, line 1)

In [8]:
1variable = 1

SyntaxError: invalid syntax (<ipython-input-8-ae24453ae98c>, line 1)

## Assignment Statements 變數賦值

In [9]:
myname = 'Kristen'

In [10]:
print(myname)

Kristen


In [11]:
yourname = hisname = hername = 'Kristen' #Multiple Assignment

In [12]:
print(yourname)

Kristen


In [13]:
print(hisname)

Kristen


In [14]:
print(hername)

Kristen


In [15]:
my_age, my_gender, my_city = 80, "Female", "Taipei" #Multiple Assignment

In [16]:
print(my_age)

80


In [17]:
print(my_gender)

Female


In [18]:
print(my_city)

Taipei


## Swap variables 交換變數

In [19]:
student1_name = 'Vincent'

In [20]:
student2_name = 'Benson'

In [21]:
print(student1_name)

Vincent


In [22]:
print(student2_name)

Benson


In [23]:
student1_name , student2_name = student2_name , student1_name

In [24]:
print(student1_name)

Benson


In [25]:
print(student2_name)

Vincent


## Data Type 資料型態

In [26]:
type(10)

int

In [27]:
type(3.14)

float

In [28]:
type(True)

bool

In [29]:
type(1>3)

bool

In [30]:
type('10')

str

### [Note] Boolean : True / False 的T和Ｆ要大寫

In [31]:
type(True)

bool

In [32]:
type(true)

NameError: name 'true' is not defined

In [33]:
type(False)

bool

In [34]:
type(false)

NameError: name 'false' is not defined

## Arithmetic Operator 算術運算子

In [35]:
1 + 2

3

In [36]:
5 - 10

-5

In [37]:
4 * 6

24

In [38]:
3 / 2

1.5

In [39]:
3 // 2

1

In [40]:
7 % 5

2

## Exercise_1
現在台北溫度是 18℃，請將℃ 轉成 ℉

In [41]:
Taipei_Celsius = 19

Taipei_Fahrenheit = Taipei_Celsius * (9/5) + 32

print(Taipei_Fahrenheit)

66.2


## Comparison Operator 關係運算子

In [42]:
x = 10

In [43]:
x < 10

False

In [44]:
x > 10

False

In [45]:
x <= 10

True

In [46]:
x >= 10

True

In [47]:
x == 10

True

In [48]:
x != 10

False

## Assignment Operator 指派運算子

In [49]:
y = 10
y += 3
print(y)

13


In [50]:
y = 10
y -= 3
print(y)

7


In [51]:
y = 10
y *= 3
print(y)

30


In [52]:
y = 10
y /= 3
print(y)

3.3333333333333335


In [53]:
y = 10
y %= 3
print(y)

1


## Logical Operator 邏輯運算子

In [54]:
(True & True)

True

In [55]:
(True & False)

False

In [56]:
(False & True)

False

In [57]:
(False & False)

False

In [58]:
(True | True)

True

In [59]:
(True | False)

True

In [60]:
(False | True)

True

In [61]:
(False | False)

False

## Data Type II 資料型態

### list

In [62]:
weather_list = [ 'Taipei' , 18.5 , 'rainy' ]

In [63]:
type(weather_list)

list

In [64]:
weather_list[0]

'Taipei'

In [65]:
weather_list[1]

18.5

In [66]:
weather_list[0:1]

['Taipei']

In [67]:
weather_list[0:3]

['Taipei', 18.5, 'rainy']

In [68]:
weather_list[:]

['Taipei', 18.5, 'rainy']

list.append(x) 

In [69]:
weather_list.append('80%') #濕度
print(weather_list)

['Taipei', 18.5, 'rainy', '80%']


In [70]:
weather_list.append(['Northeast',4]) #風相關[風向,風力級]
print(weather_list)

['Taipei', 18.5, 'rainy', '80%', ['Northeast', 4]]


In [71]:
type(weather_list[4])

list

list.extend(x)

In [72]:
weather_list.extend(['Kaohsiung',25.9,'sunny','69%'])
print(weather_list)

['Taipei', 18.5, 'rainy', '80%', ['Northeast', 4], 'Kaohsiung', 25.9, 'sunny', '69%']


In [73]:
weather_list.append(('Northwest',3)) #風相關[風向,風力級]
print(weather_list)

['Taipei', 18.5, 'rainy', '80%', ['Northeast', 4], 'Kaohsiung', 25.9, 'sunny', '69%', ('Northwest', 3)]


list.insert(index,x)

In [74]:
weather_list.insert(5,'Taichung') 
weather_list.insert(6,21.5) 
weather_list.insert(7,'cloudy')
weather_list.insert(8,'73%')
weather_list.insert(9,['North'])
print(weather_list)

['Taipei', 18.5, 'rainy', '80%', ['Northeast', 4], 'Taichung', 21.5, 'cloudy', '73%', ['North'], 'Kaohsiung', 25.9, 'sunny', '69%', ('Northwest', 3)]


## Exercise_2

In [75]:
weather_list[9].insert(len(weather_list[9]),2)
print(weather_list)

['Taipei', 18.5, 'rainy', '80%', ['Northeast', 4], 'Taichung', 21.5, 'cloudy', '73%', ['North', 2], 'Kaohsiung', 25.9, 'sunny', '69%', ('Northwest', 3)]


### tuple

In [76]:
weather_tuple = ( 'Taipei' , 'rainy', 'Taichung' , 'cloudy' , 'Tainan' , 'sunny' , 'Kaohsiung', 'sunny' )

In [77]:
type(weather_tuple)

tuple

In [78]:
weather_tuple.append('Keelung') 

AttributeError: 'tuple' object has no attribute 'append'

tuple.count(x)

In [79]:
weather_tuple.count('sunny')

2

tuple.index(x)

In [80]:
weather_tuple.index('Taipei')

0

### dictionary

In [81]:
weather_dict = { 'Taipei':'rainy', 'Taichung':'cloudy' , 'Tainan':'sunny' , 'Kaohsiung':'sunny' }

In [82]:
type(weather_dict)

dict

In [83]:
weather_dict = { 'Taipei':'rainy', 'Taichung':'cloudy' , 'Tainan':'sunny' , 'Kaohsiung':'sunny' , 'Kaohsiung':'rainy'}

In [84]:
print(weather_dict)

{'Kaohsiung': 'rainy', 'Taichung': 'cloudy', 'Tainan': 'sunny', 'Taipei': 'rainy'}


In [85]:
weather_dict = { 'Taipei':[18.5,'rainy','80%', 'Northeast', 4], 'Taichung': [21.5, 'cloudy', '73%', 'North', 2] }

In [86]:
print(weather_dict)

{'Taichung': [21.5, 'cloudy', '73%', 'North', 2], 'Taipei': [18.5, 'rainy', '80%', 'Northeast', 4]}


In [87]:
weather_dict['Taipei']

[18.5, 'rainy', '80%', 'Northeast', 4]

## Data Type Conversion

int(x)

In [88]:
int('10')

10

In [1]:
type(int('10'))

int

In [89]:
int(3.14)

3

float(x)

In [90]:
float('10')

10.0

In [91]:
float(10)

10.0

str(x)

In [92]:
str(10)

'10'

In [93]:
str(3.14)

'3.14'

In [94]:
str(weather_list)

"['Taipei', 18.5, 'rainy', '80%', ['Northeast', 4], 'Taichung', 21.5, 'cloudy', '73%', ['North', 2], 'Kaohsiung', 25.9, 'sunny', '69%', ('Northwest', 3)]"

In [95]:
str(weather_tuple)

"('Taipei', 'rainy', 'Taichung', 'cloudy', 'Tainan', 'sunny', 'Kaohsiung', 'sunny')"

In [96]:
str(weather_dict)

"{'Taichung': [21.5, 'cloudy', '73%', 'North', 2], 'Taipei': [18.5, 'rainy', '80%', 'Northeast', 4]}"

list(x)

In [97]:
list('10')

['1', '0']

In [98]:
list(weather_tuple)

['Taipei',
 'rainy',
 'Taichung',
 'cloudy',
 'Tainan',
 'sunny',
 'Kaohsiung',
 'sunny']

In [99]:
list(weather_dict)

['Taichung', 'Taipei']

tuple(x)

In [100]:
tuple('10')

('1', '0')

In [101]:
tuple(weather_list)

('Taipei',
 18.5,
 'rainy',
 '80%',
 ['Northeast', 4],
 'Taichung',
 21.5,
 'cloudy',
 '73%',
 ['North', 2],
 'Kaohsiung',
 25.9,
 'sunny',
 '69%',
 ('Northwest', 3))

## Numpy

In [3]:
import numpy

In [103]:
numpy.array([1,2,3])

array([1, 2, 3])

In [104]:
weather_array = numpy.array([ 'Taipei' , 18.5 , 'rainy' ])

In [105]:
print(weather_array)

['Taipei' '18.5' 'rainy']


In [4]:
weather_list = [ 'Taipei' , 18.5 , 'rainy' ]
weather_array2 = numpy.array(weather_list)

In [5]:
print(weather_array2)

['Taipei' '18.5' 'rainy']


In [6]:
type(weather_array2)

numpy.ndarray

In [108]:
import numpy as np

In [109]:
Temperature_Taipei = np.array([24,23,24,19,20,22,22])

In [110]:
print(Temperature_Taipei)
print(type(Temperature_Taipei))

[24 23 24 19 20 22 22]
<class 'numpy.ndarray'>


In [111]:
Temperature_Taipei.mean()

22.0

In [112]:
np.mean(Temperature_Taipei)

22.0

In [113]:
np.std(Temperature_Taipei)

1.7728105208558367

In [7]:
a = [22 , 15, 18]

In [8]:
type(a)

list

In [9]:
b = numpy.array([22 , 15, 18])

In [10]:
type(b)

numpy.ndarray

In [12]:
b * (9/5) +32

array([ 71.6,  59. ,  64.4])